name: Pull changes from Avrae

on:
  workflow_call:
    inputs:
      collections:
        description: Relative path to a JSON file containing a JSON object mapping relative directory paths in the repo to Avrae collection ids.
        default: collections.json
        required: false
        type: string
      gvars:
        description: Relative path to a JSON file containing a JSON object mapping Avrae gvar ids to descriptive names.
        default: gvars.json
        required: false
        type: string
    secrets:
      avrae_token:
        description: An authentication token from https://avrae.io/dashboard
        required: true

jobs:
  deploy_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Pull changes from Avrae
        env:
          AVRAE_TOKEN: ${{ secrets.avrae_token }}
        run: |
          env